source: .
destination: ./_site
plugins: ./_plugins
sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: false
exclude:
  - adoc.*
  - Gemfile*
  - config.rb
  - pry-test.rb
  - sass
